--- #YAML:1.0
name:                     CPAN-Testers-Fact-PlatformInfo
version:                  1.00
abstract:                 Platform information on which a CPAN Testers smoker is running.
author:
  - Barbie (BARBIE) <barbie@cpan.org>
  - Brian McCauley (NOBULL) <nobull67@gmail.com>
  - Colin Newell http://colinnewell.wordpress.com/
  - Jon 'JJ' Allen (JONALLEN) <jj@jonallen.info>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Carp:                   0
  Metabase::Fact::Hash:   0.016
recommends:
  Test::More:             0.70
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.13
  Test::CPAN::Meta::JSON: 0.10
build_requires:
  Test::More:             0.70

provides:
  CPAN::Testers::Fact::PlatformInfo:
    file:     lib/CPAN/Testers/Fact/PlatformInfo.pm
    version:  1.00

no_index:
  directory:
    - t

resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-Fact-PlatformInfo
  repository: git://github.com/barbie/cpan-testers-fact-platforminfo.git

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
